### ISSUE TITLE
Strange things around sides of the frequency plots

### ISSUE THREAD

**Issue by PeterLidsky** [ptdolan/CirQuestDSV#2]
Some frequency lines are ending up at passage 2 and passage 6 in both sets of passages. 
[Persist dir_log_TrajPlot.pdf](https://github.com/ptdolan/CirQuestDSV/files/379198/Persist.dir_log_TrajPlot.pdf)
[Acute dir_log_TrajPlot.pdf](https://github.com/ptdolan/CirQuestDSV/files/379199/Acute.dir_log_TrajPlot.pdf)
[Persist dir_sqrt_TrajPlot.pdf](https://github.com/ptdolan/CirQuestDSV/files/379202/Persist.dir_sqrt_TrajPlot.pdf)
[Acute dir_sqrt_TrajPlot.pdf](https://github.com/ptdolan/CirQuestDSV/files/379201/Acute.dir_sqrt_TrajPlot.pdf)

**Comment by PeterLidsky** [comment]
It would be also great to generate a csv with all mutation frequencies summarized passagewise:
E.g. T->C at position XYZ, leading to S->G AA substitution, and its freqs for this mutation in all passages.

**Comment by ptdolan** [comment]
The reason these are disappearing is because I am using filtered values, will revert to unfiltered for trajectories so lines are continuous. I will also add combined output of trajectory in plot.

**Comment by PeterLidsky** [comment]
Filtered by what? Being above zero? Or by some quality?

**Comment by ptdolan** [comment]
By reliability of the frequency measured (basically must be greater than 3 identified reads in total coverage), based on binomial sampling.

**Comment by PeterLidsky** [comment]
hmmm... is it still needed in cirseq analyses? Sorry for a stupid question.

**Comment by ptdolan** [comment]
From the simulation attached you can see the effect of low coverage on the observed allele frequency. estimations (histogram of 10000 samples) of the red line (actual allele frequency) are either 0 or much higher when the coverage is equal or less than the true frequency. One can have very good certainty for if the count of the allele (regardless of coverage) is 3 or greater. 

[Sim_CoverageAndFrequencies.pdf]
[Sim_CoverageAndFrequencies.pdf](https://github.com/ptdolan/CirQuestDSV/files/379234/Sim_CoverageAndFrequencies.pdf)

**Comment by ptdolan** [comment]
OK, I have fixed all of this. Give it a shot and if the outputs work for you, close the issue. Thanks, Peter.

**Comment by PeterLidsky** [comment]
Yes, it works..
