### ISSUE TITLE
Issues!

### ISSUE THREAD

**Issue by yinghongxiao** [ptdolan/CirQuestDSV#4]
Hi Patrick,
This script works. However, for me, in output files it only generated figure(one Manhattaanplot and one Entropy) and table for  last passage  if I have  multi-Q20s. And No DirFre_table or Figure generate.
What I did: 
I did Q20Analysis.py, it  works well.
I only changed one line in Rscript: rootDir<- "/Users/yinghongxiao/desktop/Miseq_test/ 
Then I did 
>R
>source("AnnotAnalysis.R")

Best,
Hong

**Comment by ptdolan** [comment]
Can you paste the command line output from R?  Thanks, Hong!

**Comment by yinghongxiao** [comment]
Hi Patrick,
Below is the command I used in terminal. Please see my Q-20 as attached file.
Thanks,
Yinghong

Terminal commands:

Last login: Sat Feb 11 19:09:59 on ttys000

Yinghongs-MacBook-Pro:~ yinghongxiao$ cd desktop

Yinghongs-MacBook-Pro:desktop yinghongxiao$ cd MiseqIFN10

Yinghongs-MacBook-Pro:MiseqIFN10 yinghongxiao$ Rscript /Users/yinghongxiao/desktop/MiseqIFN10/AnnotAnalysis.R /Users/yinghongxiao/desktop/MiseqIFN10/

[1] "Generating R plots and text outputs..."

Loading required package: limma

Loading required package: ggplot2

Loading required package: reshape2

[1] "/Users/yinghongxiao/desktop/MiseqIFN10//IFN10_1-Q20_annot.txt"

[1] "Header: MiseqIFN10 Passage: IFN10_1"

[1] "/Users/yinghongxiao/desktop/MiseqIFN10//IFN10_2-Q20_annot.txt"

[1] "Header: MiseqIFN10 Passage: IFN10_2"

[1] "/Users/yinghongxiao/desktop/MiseqIFN10//IFN10_3-Q20_annot.txt"

[1] "Header: MiseqIFN10 Passage: IFN10_3"

[1] "/Users/yinghongxiao/desktop/MiseqIFN10//IFN10_4-Q20_annot.txt"

[1] "Header: MiseqIFN10 Passage: IFN10_4"

Error in strsplit2(rownames(distDF), split = "_")[, 4] :

  subscript out of bounds

In addition: There were 12 warnings (use warnings() to see them)

Execution halted


________________________________

**Comment by ptdolan** [comment]
OK, I think I fixed it. Should be working. If you can give it a try again, let me know if it works.

**Comment by yinghongxiao** [comment]
I will try it today, thanks, Patrick!
Have a nice day!
Hong

Sent from my iPhone

On Feb 14, 2017, at 12:17 AM, Patrick Dolan <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, I think I fixed it. Should be working. If you can give it a try again, let me know if it works.

**Comment by yinghongxiao** [comment]
The script works pretty well now, thank you very much, Patrick!
Best,
Hong
________________________________
